### ISSUE TITLE
Adjust font sizes, line height and container-width

### ISSUE THREAD

**Issue by vis9494** [ampcc/coding-challenge#144]
Applies to: app, start, admin login, admin password, button, and dialog components

- [x] Width of .main_container to 75%
- [x] font size of smallest text to 16px
- [x] font size of medium text to 20px
- [x] font size of titles to 50px
- [x] font size of smallest text to 25px on screens wider than 2000px
- [x] font size of medium text to 30px on screens wider than 2000px
- [x] font size of titles to 50px on screens wider than 2000px
- [x] adjust button width on password and login
- [x] set footer to be displayed lower

**Comment by lorenzschreyer** [comment]
@vis9494 @vew7531  recommendation: it would be great if the default text is displayed in the google font: https://fonts.google.com/specimen/Catamaran, and only headers in font: https://fonts.google.com/specimen/Comfortaa

this is also the case on the official website of https://amplimind.io/

**Comment by vew7531** [comment]
@lorenzschreyer The whole thing is intentionally designed this way because we are not orienting ourselves to the general website but to the job portal in the design. There, only the font "Comfortaa" is used.
