### ISSUE TITLE
Implementation of Application and Challenge

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#15]
Create Python Classes:

1.  #17 -> [Definition of application](https://github.com/ampcc/coding-challenge/wiki/API-Documentation-for-admin-functions#success-response-1)
2. #18 -> [Definition of challenge](https://github.com/ampcc/coding-challenge/wiki/API-Documentation-for-admin-functions#success-response-8)

with unittests ( #13 )

**Comment by hamteer** [comment]
- [ ] #17 
- [ ] #18

**Comment by lorenzschreyer** [comment]
Definition has changed. Current is visible in wiki

**Comment by lorenzschreyer** [comment]
Problem: its not defined now how to deal with authentication in django. Perhaps `applicationKey` and `applicationId` has to be in a seperate model, that supports authentication
