### ISSUE TITLE
upload Challenge with githubApi

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#197]
implements #184 
- [x] #194

**Comment by lorenzschreyer** [comment]
<img width="1351" alt="Bildschirmfoto 2023-05-02 um 20 12 35" src="https://user-images.githubusercontent.com/46090335/235750305-a991eed4-047f-4d08-8694-f1abfff61a8f.png">

**Comment by KRIYO144** [comment]
Note:

The response of UploadChallenge can take a prolonged time

**Comment by lorenzschreyer** [comment]
new requirement: scan for correct folder structure
