### ISSUE TITLE
Linting only for files in correct folder

### ISSUE THREAD

**Issue by hamteer** [ampcc/coding-challenge#204]

**Comment by lorenzschreyer** [comment]
Who defines what the correct folder is?
currently there is no option for the user to fedine the "correct" folder, and in backend only raw compressed data arrives.

The metadata like filename, extension or mediatype are defined by the post header and not by the file uploaded.
This could be really difficult to implement

**Comment by lorenzschreyer** [comment]
@langtobi98 fyi
