### ISSUE TITLE
Pass Exceptions from Github

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#233]
Exceptions that appear from github (e.g. createRepo failed because the repo already exists), should be passed and a Response with the correct status code and message should be created

**Comment by lorenzschreyer** [comment]
implemented by #206

**Comment by Marcodaum** [comment]
wouldn't it be good to combine this task with the testing procedure? Will have huge impact on the new tests that use/affect the Github API...

**Comment by lorenzschreyer** [comment]
- maybe the possible results should be linked in Wiki 
- maybe the documentation url should be passed too
