### ISSUE TITLE
Test Github Rest API to create repos automatically

### ISSUE THREAD

**Issue by Marcodaum** [ampcc/coding-challenge#24]
Idea: test out api calls with ssh key on github rest api

**Comment by lorenzschreyer** [comment]
- [create organisation repositories](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository--code-samples)
- [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token#creating-a-personal-access-token-classic)

**Comment by lorenzschreyer** [comment]
Code for getting all repos under ampcc

```
curl -L -H "Accept: application/vnd.github+json" -H "Authorization: f7b4b47993ce3f646dadf953433e2770db3e407f" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/orgs/ampcc/repos
```

More Calls -> [create organisation repositories](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#create-an-organization-repository--code-samples)

**Comment by KRIYO144** [comment]
Created GitHub App in Organisation 

https://github.com/organizations/ampcc/settings/installations/36314312

The Authentication for the API Calls is managed in this App.

**Comment by lorenzschreyer** [comment]
Deleted GitHub App because there is a better way to authenticate in a workflow.
[feature/test-github-api](https://github.com/ampcc/coding-challenge/blob/feature/test-github-api/.github/workflows/testGithubApi.yml)

**Comment by lorenzschreyer** [comment]
Changed Authentication Type to GithubApp

**Comment by Marcodaum** [comment]
@lorenzschreyer Is this GitHub Access-Token, that is exposed in your second comment security-critical? If yes we have to recreate one.
