### ISSUE TITLE
Zip Upload Folder Structure Bug

### ISSUE THREAD

**Issue by KRIYO144** [ampcc/coding-challenge#300]
It is possible to just upload a zip which has only text files on top level. 

Example.zip
├── test1.txt
├── test2.txt
└── test3.txt

**Comment by Marcodaum** [comment]
@KRIYO144  Why is this a problem? I thought it just isn't allowed to have no file at top-level...

**Comment by Marcodaum** [comment]
@KRIYO144 understood problem. Will be fixed in the upcoming PR.
