### ISSUE TITLE
Django SECRET_KEY in settings exposed

### ISSUE THREAD

**Issue by Marcodaum** [ampcc/coding-challenge#34]
SECRET_KEY should not be pushed to repo. Move SECRET_KEY to .env-file.

**Comment by lorenzschreyer** [comment]
Maybe the SECRET_KEY can be a Github Secret Variable of the Repository https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by FabianBretz** [comment]
@lorenzschreyer i can look further into that. For now a sollution with an .env file is implemented

**Comment by FabianBretz** [comment]
From what i've found, Github secrets (encrypted secrets) are only useable inside Github actions.
Therefor you can't use them inside the productive code itself

**Comment by dak2791** [comment]
.env distributed and branch merged
