### ISSUE TITLE
OS and Programming Language in upload Solution is not submitted

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#341]
The problem is, that only raw data is passed in the body.

My suggestion: Append a file to the zip which includes the OS and Programming Language

**Comment by KRIYO144** [comment]
Resolved. A generated README.md is now pushed onto .github folder. The generated File contains ApplicationID, OS, Programming language, ChallengeID and Challengeheading and Text. 

The generated README.md is shown on the main page of the repo. A Readme from the Applicant is still on root level but isnt shown on the main page. (It isnt being overridden)
