### ISSUE TITLE
"challengeId" in Wiki is different to "id" in Code

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#343]

**Comment by Marcodaum** [comment]
can you give me an example? I am not sure what you mean...

**Comment by lorenzschreyer** [comment]
For example the API-Call `get Challenges` returns a Lost of challenges with `id`, `challengeHeading`, `challengeText`.

in Wiki its described to return a List of challenges with `challengeId`, `challengeHeading`, `challengeText`.

**Comment by Marcodaum** [comment]
Oof. So it's just about changing the parameter `id` to`challengeId`?

**Comment by lorenzschreyer** [comment]
@Marcodaum yes
