### ISSUE TITLE
EXPIRED Status is faulty

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#344]
The `EXPIRED `Status is set when an applicant calls the api call **startChallenge**, but is expired by the timestamp (set on creation). 
So if an applicant never starts a challenge, this status will never be set.

If the frontend is using the status instead of computing the expiry through the given timestamp, some expired Applicants will not be shown.

Solutions can be:
1. remove `status.EXPIRED` and use the timestamp in frontend
2. keep `status.EXPIRED` and add a database trigger to keep the `expiry `Timestamp and the `EXPIRED `Status equal

**Comment by FabianBretz** [comment]
Similar mention already in #93
