### ISSUE TITLE
Refactoring of the Backends views-folder

### ISSUE THREAD

**Issue by Marcodaum** [ampcc/coding-challenge#395]
Splitting of all calls into separate files and classes for better overview and easier debugging

**Comment by ThmsRchhrzr** [comment]
Splitting of all calls into separate files and classes for better overview and easier debugging

**Comment by ThmsRchhrzr** [comment]
![grafik](https://github.com/ampcc/coding-challenge/assets/94746024/b9b73eab-995b-4d7e-8fba-c70ce0269e96)
