### ISSUE TITLE
[interface] implementation of getChallenge (application)

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#52]
https://github.com/ampcc/coding-challenge/wiki/API-Documentation-for-applicant-functions#5-get-challenge

**Comment by FabianBretz** [comment]
Tbd:

- Implement test cases
- Refactor code to match structure of develop
- Change way of receiving applicationId to **kwargs
- Change authentication of application as suggested by @Marcodaum
