### ISSUE TITLE
[interface] implementation of createApplication (admin)

### ISSUE THREAD

**Issue by lorenzschreyer** [ampcc/coding-challenge#62]
https://github.com/ampcc/coding-challenge/wiki/API-Documentation-for-admin-functions#createApplication

**Comment by KRIYO144** [comment]
Optional argument "Days" is now implemented as the expiry date before the User calls startChallenge. The expiry date should be changed after the call startChallenge. 

Previously the idea behind this variable "Days" was to set the Value of the expiry Date for the completion of the coding challenge.

At the moment it is not possible to change expiry date after calling startChalellenge.

**Comment by lorenzschreyer** [comment]
Added 422 Error Code: because no challenge can be randomly selected if no challenge is existing
